### ISSUE TITLE
parse complex mathematical expressions from input file using sympy

### ISSUE THREAD

**Issue by rvignolo** [sympy/sympy#17559]
Hi all, 

I am trying to implement a nice parser of mathematical expressions in python. My input file is in `yaml` format. I would like to handle algebraic functions (coming from algebraic expressions) and pointwise functions (coming from interpolation of data). So for example, in the input file one may find something like this:

```yml
Functions:

  f(t,x):
    type: algebraic
    expression: t**2 + 2 * x + 1

  g(t,x):
    type: algebraic
    expression: t - 1 + f(t, x)

  h(t):
    type: pointwise
    method: Bspline
    xdata: ...
    fdata: ...

# once we have the previous functions defined in the input file, we can use
# them for more complex expressions in other input fields, for example:
Processes:
  
  r:
    drift: 2 * h(t) + g(t, r_t) - cos(t)
    ...
```

So far, in order to be able to handle this kind of expressions I code something like the following snippet (please, we aware that this is a minimal working example and it does not include all the parsing of the `yaml` file):

```python
import numpy
from sympy import *
from sympy.printing.theanocode import theano_function
from sympy.utilities.autowrap import ufuncify

# begin with the first function f(t,x)
# parse function name
f_name = 'f'

# parse symbols used as arguments and define them (if they not already defined)
t = Symbol('t')
x = Symbol('x')

# parse expression string
f_expr_string = 't**2 + 2 * x + 1'

# convert string to sympy expression
f_expr = sympify(f_expr_string)

# define functions using different methods 
f_numpy = lambdify((t, x), f_expr, 'numpy')
f_ufunc = ufuncify((t, x), f_expr, backend='Cython')  # 'f2py' or 'numpy' are also supported
f_theano = theano_function([t, x], [f_expr])

# test evaluations
print(f_numpy(2, 0.1))
print(f_ufunc(numpy.array([2.0]), numpy.array([0.1])))
print(f_theano(2, 0.1))

# define a dictionary with all the already defined functions
func_dict = {f_name: f_numpy}

# continue with the second function g(t,x)
# parse function name
g_name = 'g'

# parse symbols used as arguments and define them (if they not already defined)
# they have been already defined

# parse expression string
g_expr_string = 't - 1 + f(t, x)'

# convert string to sympy expression
g_expr = sympify(g_expr_string)

# define functions using different methods (ufuncify and theano do not work because I was not able to pass a func_dict to them)
g_numpy = lambdify((t, x), g_expr, [func_dict, 'numpy'])
# g_ufunc = ufuncify((t, x), g_expr, backend='Cython')  # 'f2py' or 'numpy' are also supported
# g_theano = theano_function([t, x], [g_expr])

# test evaluation
print(g_numpy(0.6, 1.5))

# update dictionary
func_dict.update({g_name: g_numpy})
```

The first issue I have encounter is that both `ufuncify` and `theano_function` cannot handle expressions that depend in other function objects. At least, I could not make them work.

The second issue I need to solve is how to implement `PointWise` functions, i.e. functions that interpolate data using an specific interpolation method. I believe I have to subclass the `Function` class to handle this approach:

```python
class PointWise(Function):
    nargs = None
```

but I am not sure. Could you provide me some insight if this is possible or not (and how would you do it) within the current Sympy version.

Thanks in advance!
